### ISSUE TITLE
もう少し短くできるのではないか

### ISSUE THREAD

**Issue by c0a21131** [C0A21113/ProjExD#10]
https://github.com/C0A21113/ProjExD/blob/49db108a018f938446789028a86d9616e070f17d/ex04/dodge_bomb.py#L57
if文が多いのでリストや辞書をfor文で回せば短くできるのではないか？

**Comment by C0A21113** [comment]
指摘ありがとうございます。
変更しようとしましたが、技術不足により変更できませんでした。
今後修正できるように頑張ります。
