### ISSUE TITLE
場所を変えた方がいい

### ISSUE THREAD

**Issue by c0a21131** [C0A21113/ProjExD#14]
https://github.com/C0A21113/ProjExD/blob/649a624efd97abb3f64f8424773e991ac5532f83/ex05/fight_kokaton.py#L137
この部分はmain()の中に入れた方がいいと思う。各クラスには引数で渡すといい。

**Comment by C0A21113** [comment]
指摘ありがとうございます。
変更しようとしましたが、うまくできませんでした。
後日変更できるように頑張ります
