### ISSUE TITLE
不必要な改行

### ISSUE THREAD

**Issue by C0A21119** [C0A21113/ProjExD#2]
https://github.com/C0A21113/ProjExD/blob/fa61d8c058f09be88c5953fe58758fc73e301421/ex01/alphabet.py#L3
#
不必要な改行がある

**Comment by C0A21113** [comment]
直しました

**Comment by C0A21113** [comment]
ありがとうございます。修正しました。

**Comment by riku2003** [comment]
いらない改行があります
