### ISSUE TITLE
長いのではないか？

### ISSUE THREAD

**Issue by c0a21131** [C0A21113/ProjExD#6]
https://github.com/C0A21113/ProjExD/blob/bb2a7d7f077e7fedaa75a49223cdf095bce6265f/ex03/maze.py#L30
if文の部分が長いと思う。
リストや辞書を使って、for文で回せば短くできるのではないか？

**Comment by C0A21113** [comment]
ご指摘の部分を変更しようと試みたが、できそうになかったのでこのままにしています。
今後改善できれば良いと考えています。
