### ISSUE TITLE
変更箇所の提案

### ISSUE THREAD

**Issue by C0A21119** [C0A21113/ProjExD#9]
https://github.com/C0A21113/ProjExD/blob/49db108a018f938446789028a86d9616e070f17d/ex04/dodge_bomb.py#L37
コメント前や内容が変わる箇所は、改行を入れるとより見やすくなると感じた。
if文は、for文に入れる等するとよりきれいに書けると感じた。

**Comment by C0A21113** [comment]
指摘ありがとうございます。
if文に関しては技術不足により変更できませんでした。
